server:
  port: 5555 # 注意，:后面要有一个空格

spring:
  activemq:
    broker-url: tcp://192.168.154.101:61616 # ActiveMQ Broker 地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # false 代表队列,true代表主题

# 自已定义的主题名称
myTopic: boot-active-topic

